### ISSUE TITLE
Use in RecyclerView

### ISSUE THREAD

**Issue by tellfa** [florent37/ExpansionPanel#1]
Hi. thanks for this great library.
how can i use this in recyclerview?

**Comment by florent37** [comment]
I have not tested yet info recyclerview

**Comment by florent37** [comment]
But just include the layout into your viewolder should work

**Comment by florent37** [comment]
check https://github.com/florent37/ExpansionPanel/blob/master/app/src/main/java/florent37/github/com/expansionpanel/SampleActivityRecycler.java
