### ISSUE TITLE
onToggleListner()

### ISSUE THREAD

**Issue by bhapps** [florent37/ExpansionPanel#10]
Hi @florent37 ,

Quick question, using java is there the function of a toggle event from code behind? (aiming to then load content when toggled)
Thanks in advance.

**Comment by florent37** [comment]
you have a listener in the ExpansionLayout

**Comment by florent37** [comment]
I updated the README ;)

**Comment by florent37** [comment]
https://github.com/florent37/ExpansionPanel#listener
