### ISSUE TITLE
A small mistake in "Usage" Description

### ISSUE THREAD

**Issue by SeyedAbdollahi** [florent37/ExpansionPanel#16]
Hi , in the part of "Usage" headerIndicator and expansionLayout ID  is defined:
`app:expansion_headerIndicator="@id/headerIndicator"`
` app:expansion_layout="@id/expansionLayout"`

That should be:
`app:expansion_headerIndicator="@+id/headerIndicator"`
`app:expansion_layout="@+id/expansionLayout"`

**Comment by florent37** [comment]
why ? you can use `@id/`

**Comment by touficbatache** [comment]
No @RezaAbdollahi2 is right, the IDE doesn't show any errors but the app crashes when I use `@id/`... I think you should update it @florent37 ;)
