### ISSUE TITLE
Header Indicator doesn't appear on right

### ISSUE THREAD

**Issue by southrop** [florent37/ExpansionPanel#17]
Hi there,

I'm trying to use this library, but I've found that using your demo code in the README, the header indicator refuses to display on the right side of the panel. For example, I have this code:

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <com.github.florent37.expansionpanel.ExpansionHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:expansion_headerIndicator="@id/description_indicator"
            app:expansion_headerIndicatorRotationCollapsed="270"
            app:expansion_headerIndicatorRotationExpanded="0"
            app:expansion_layout="@id/description_layout">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Test Test Test" />

            <ImageView
                android:id="@+id/description_indicator"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:layout_marginLeft="16dp"
                android:layout_marginStart="16dp"
                app:srcCompat="@drawable/ic_expand" />

        </com.github.florent37.expansionpanel.ExpansionHeader>

        <com.github.florent37.expansionpanel.ExpansionLayout
            android:id="@+id/description_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="Blah blah blah" />

        </com.github.florent37.expansionpanel.ExpansionLayout>

    </LinearLayout>

which produces this result:

![studio64_2018-02-27_12-45-35](https://user-images.githubusercontent.com/2568167/36709627-2c28b02a-1bbc-11e8-8f7c-ccb3f06be050.png)

I was able to resolve the issue by replacing the `layout_alignParentRight/End` attributes with a `android:layout_gravity="end"` on the indicator, but is this the right solution? If so, the README should probably be updated to reflect this.

**Comment by florent37** [comment]
Because alignParentEnd only work inside relativeLayout

**Comment by florent37** [comment]
It's the samedi if you use a cardview

Le 27 févr. 2018 08:03, "Florent Champigny" <champigny.florent@gmail.com> a
écrit :

> Because alignParentEnd only work inside relativeLayout
>

**Comment by florent37** [comment]
ExpansionHeader extends FrameLayout

**Comment by southrop** [comment]
Hi,

That's fine, it's not really an issue for me. But your usage example in the README has `alignParentRight` in it too. Perhaps that should be updated if it isn't supposed to work?

        
        <android.support.v7.widget.AppCompatImageView
               android:adjustViewBounds="true"
               android:id="@+id/headerIndicator"
               android:layout_alignParentRight="true"
               android:layout_centerVertical="true"
               android:layout_height="wrap_content"
               android:layout_marginLeft="16dp"
               android:layout_width="wrap_content"
               app:srcCompat="@drawable/ic_expansion_header_indicator_grey_24dp" />

**Comment by florent37** [comment]
oh I update the readme

**Comment by florent37** [comment]
```
 <!-- HEADER INDICATOR -->
        <android.support.v7.widget.AppCompatImageView
               android:adjustViewBounds="true"
               android:id="@+id/headerIndicator"
               android:layout_gravity="center_vertical|right"
               android:layout_height="wrap_content"
               android:layout_marginLeft="16dp"
               android:layout_width="wrap_content"
               app:srcCompat="@drawable/ic_expansion_header_indicator_grey_24dp" />

```
