### ISSUE TITLE
Scrolling recyclerview collapses all expanded view

### ISSUE THREAD

**Issue by monowar1993** [florent37/ExpansionPanel#22]
I have expanded some view on top of recyclerview, then scroll to bottom. When I scroll back again to the top the expanded views are collapsed.

**Comment by florent37** [comment]
do you save the expanded view state on your viewholder ?

**Comment by florent37** [comment]
https://github.com/florent37/ExpansionPanel/blob/master/app/src/main/java/florent37/github/com/expansionpanel/SampleActivityRecycler.java

**Comment by monowar1993** [comment]
no I am not.

**Comment by Peterragheb** [comment]
I'm facing this issue.
It doesn't save the state of the expandable layout.
