### ISSUE TITLE
How to add different label name in SampleActivityProgrammatically?

### ISSUE THREAD

**Issue by trionohidayat** [florent37/ExpansionPanel#23]
I know how to add labels in SampleActivityProgrammatically.Java but I do not know how to change the label name. I hope you can help me, sir.

![activityprogrammatically1](https://user-images.githubusercontent.com/17020791/39006083-35776ec6-442c-11e8-9bab-0e4008819d6f.png)
![activityprogrammatically2](https://user-images.githubusercontent.com/17020791/39006086-35b208ec-442c-11e8-99d8-41de79083c0a.png)

**Comment by adriantache** [comment]
Just give the label `TextView` an ID, find that view and `setText` on it.

**Comment by florent37** [comment]
you just have to use a custom view inside the header, it works like a linear layout or relativelayout
