### ISSUE TITLE
Change icon when expanded and collapsed

### ISSUE THREAD

**Issue by pasaneramusugoda** [florent37/ExpansionPanel#25]
would like to request a new feature about changing icon when expanded and collapsed.
This project ("com.github.ivbaranov.mfb.MaterialFavoriteButton" google this) already have above functionality.

**Comment by florent37** [comment]
You Can listen to expansion/collapse, do you Can Do manually.

Le dim. 29 avr. 2018 à 06:19, pasaneramusugoda <notifications@github.com> a
écrit :
