### ISSUE TITLE
Animate expand icon differently

### ISSUE THREAD

**Issue by touficbatache** [florent37/ExpansionPanel#28]
Hey!
What about using [this](https://github.com/zagum/Android-ExpandIcon) instead of the expand icon used now? It looks better and is used in Android by Google itself!

**Comment by florent37** [comment]
the icon I used is only an imageview, I will not force users to have an implementation of expanded / collapsed icon, I just give the expandable view & a header that follows his expansion.

You're free to use this lib with mine in you project
