### ISSUE TITLE
Feedback ExpansionPanel Problem

### ISSUE THREAD

**Issue by tcqq** [florent37/ExpansionPanel#4]
Hello, thankyou your library, In RecyclerView activity have a problem, when i opne item1, and than i scroll item, the other item also will open.

**Comment by florent37** [comment]
It's the principe if recyclerview ;) try tout Gone a view then scroll

**Comment by florent37** [comment]
I did not saved the state un my sample

Le 10 janv. 2018 08:05, "Florent Champigny" <champigny.florent@gmail.com> a
écrit :

> It's the principe if recyclerview ;) try tout Gone a view then scroll
>

**Comment by tcqq** [comment]
Ok, thankyou.
