### ISSUE TITLE
Gradle sync fails using 1.2.0

### ISSUE THREAD

**Issue by deano2390** [florent37/ExpansionPanel#40]
If I try to use version 1.2.0, gradle sync fails every time.

Downgrading to 1.1.1 get's it working again.

Unfortunately Android Studio is not telling me what the problem is at all.

**Comment by MenosGrante** [comment]
Looks like update was not pushed to Maven repository, so it is not available for Gradle/Maven yet.

**Comment by benyAlves** [comment]
How long it will take to make it available?

**Comment by florent37** [comment]
I published the 1.2.2,
sorry for the upload
