### ISSUE TITLE
Feedback ExpansionPanel Problem

### ISSUE THREAD

**Issue by tcqq** [florent37/ExpansionPanel#6]
Hi, how to set ExpansionHeader default open and close status, and listener ExpansionHeader open and close status?

**Comment by florent37** [comment]
The header follow the ExpansionLayout, so just change the default status of
ExpansionLayout, the header will follow

you have an attribute app:expanded="false", or .setExpanded(animated)

and you can add a listener, but on the ExpansionLayout, not on the header

2018-01-11 7:46 GMT+01:00 TCQQ <notifications@github.com>:

**Comment by tcqq** [comment]
ExpansionLayout not have setExpanded, where is setExpanded?

![qq 20180112084135](https://user-images.githubusercontent.com/10644057/34854387-6d505330-f774-11e7-9c33-dc4657ddca83.png)

**Comment by tcqq** [comment]
I find the addIndicatorListener thankyou.

**Comment by florent37** [comment]
.expand(animated)

**Comment by tcqq** [comment]
thankyou
