### ISSUE TITLE
Feedback ExpansionPanel RTL bug

### ISSUE THREAD

**Issue by tcqq** [florent37/ExpansionPanel#7]
The icon is reversed in RTL mode

![image](https://user-images.githubusercontent.com/10644057/34896448-dd79fbce-f824-11e7-84d0-2de3754d5c6e.png)
![image](https://user-images.githubusercontent.com/10644057/34896463-eda12ebe-f824-11e7-8d4a-42534d97736f.png)

![image](https://user-images.githubusercontent.com/10644057/34896536-282ac720-f825-11e7-802b-894841af2b18.png)

**Comment by florent37** [comment]
You Can make a pull request if you want to fix it

**Comment by tcqq** [comment]
#8

**Comment by florent37** [comment]
1.0.6
