### ISSUE TITLE
Set custom background to ExpansionHeader

### ISSUE THREAD

**Issue by tellfa** [florent37/ExpansionPanel#9]
I want set custom background fro ExpansionHeader with positions in adapter.

how can it?

**Comment by florent37** [comment]
it's a extension of framelayout,so you can change the background as a normal view

**Comment by tellfa** [comment]
Thanks my friend, i set android:background="000" in ExpansionHeader, but not set color !

**Comment by florent37** [comment]
000 is not a color

**Comment by tellfa** [comment]
my mean is "#000000" my bro

**Comment by florent37** [comment]
we use this in my project, so I can tell you it's working
